{
    "summary": {
        "num_errors": 0,
        "num_failures": 1,
        "num_skips": 0,
        "num_tests": 1
    },
    "tests": [
        {
            "data": {
                "inputs": {
                    "input_data": {
                        "id": "bfd93254e53107a0",
                        "src": "hda"
                    }
                },
                "job": {
                    "command_line": "python '/home/giuliano/Scaricati/trends_earth/galaxy_fix_tool/te_productivity.py' '/media/agritech/tmp/tmpsmdvi0sb/files/0/2/3/dataset_023118e2-5846-4709-9677-964ef7b02dcf.dat' '/home/giuliano/Scaricati/trends_earth/galaxy_fix_tool/key.json'",
                    "command_version": "",
                    "create_time": "2023-05-17T17:33:59.802418",
                    "dependencies": [],
                    "exit_code": 1,
                    "external_id": "690687",
                    "galaxy_version": "23.0",
                    "history_id": "bfd93254e53107a0",
                    "id": "222c3399dbf7a671",
                    "inputs": {
                        "input_data": {
                            "id": "bfd93254e53107a0",
                            "src": "hda",
                            "uuid": "023118e2-5846-4709-9677-964ef7b02dcf"
                        }
                    },
                    "job_messages": [
                        {
                            "code_desc": "",
                            "desc": "Fatal error: Exit code 1 ()",
                            "error_level": 3,
                            "exit_code": 1,
                            "type": "exit_code"
                        }
                    ],
                    "job_metrics": [],
                    "job_stderr": "",
                    "job_stdout": "",
                    "model_class": "Job",
                    "output_collections": {},
                    "outputs": {
                        "output_geojson": {
                            "id": "222c3399dbf7a671",
                            "src": "hda",
                            "uuid": "10ebaed7-ead7-47b0-8110-8021ed4bce29"
                        }
                    },
                    "params": {
                        "__input_ext": "\"input\"",
                        "chromInfo": "\"/media/agritech/tmp/tmpsmdvi0sb/galaxy-dev/tool-data/shared/ucsc/chrom/?.len\"",
                        "dbkey": "\"?\""
                    },
                    "state": "error",
                    "stderr": "Loading parameters.\nExecution ID is None\nRunning productivity indicators.\nEntering productivity_trajectory function.\nEntering p_restrend function\nEntering ndvi_trend function.\nEntering linear_trend function\nEntering productivity_performance function.\nEntering productivity_state function.\nConverting output to TEImageV2 format\nExporting to cloud storage.\nStarting GEE task AD4ISJNXKALSHVXMHTC4KIFG.\nException in thread Thread-1:\nTraceback (most recent call last):\n  File \"/home/giuliano/miniconda3/envs/mulled-v1-dcee9f26cd5ca519fee179179957a800bc006c97a59b7cffcad22418ef2b96aa/lib/python3.11/threading.py\", line 1038, in _bootstrap_inner\n    self.run()\n  File \"/home/giuliano/miniconda3/envs/mulled-v1-dcee9f26cd5ca519fee179179957a800bc006c97a59b7cffcad22418ef2b96aa/lib/python3.11/site-packages/te_algorithms/gee/util.py\", line 115, in run\n    self.poll_for_completion()\n  File \"/home/giuliano/miniconda3/envs/mulled-v1-dcee9f26cd5ca519fee179179957a800bc006c97a59b7cffcad22418ef2b96aa/lib/python3.11/site-packages/te_algorithms/gee/util.py\", line 109, in poll_for_completion\n    return get_status(self)\n           ^^^^^^^^^^^^^^^^\n  File \"/home/giuliano/miniconda3/envs/mulled-v1-dcee9f26cd5ca519fee179179957a800bc006c97a59b7cffcad22418ef2b96aa/lib/python3.11/site-packages/backoff/_sync.py\", line 48, in retry\n    ret = target(*args, **kwargs)\n          ^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/giuliano/miniconda3/envs/mulled-v1-dcee9f26cd5ca519fee179179957a800bc006c97a59b7cffcad22418ef2b96aa/lib/python3.11/site-packages/te_algorithms/gee/util.py\", line 104, in get_status\n    self.logger.send_progress(self.task.status().get(\"progress\", 0.0))\n    ^^^^^^^^^^^^^^^^^^^^^^^^^\nAttributeError: 'Logger' object has no attribute 'send_progress'\nFailed to list uris for results from <Task AD4ISJNXKALSHVXMHTC4KIFG EXPORT_IMAGE: None_1_productivity_Int16_1 (UNSUBMITTED)>\nTraceback (most recent call last):\n  File \"/home/giuliano/Scaricati/trends_earth/galaxy_fix_tool/te_productivity.py\", line 51, in <module>\n    output_data = productivity.run(params=input_data, logger = logger)\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/giuliano/Scaricati/trends_earth/galaxy_fix_tool/productivity.py\", line 148, in run\n    final_output = schema.load(res[0].result())\n                               ^^^^^^^^^^^^^^^\n  File \"/home/giuliano/miniconda3/envs/mulled-v1-dcee9f26cd5ca519fee179179957a800bc006c97a59b7cffcad22418ef2b96aa/lib/python3.11/concurrent/futures/_base.py\", line 449, in result\n    return self.__get_result()\n           ^^^^^^^^^^^^^^^^^^^\n  File \"/home/giuliano/miniconda3/envs/mulled-v1-dcee9f26cd5ca519fee179179957a800bc006c97a59b7cffcad22418ef2b96aa/lib/python3.11/concurrent/futures/_base.py\", line 401, in __get_result\n    raise self._exception\n  File \"/home/giuliano/miniconda3/envs/mulled-v1-dcee9f26cd5ca519fee179179957a800bc006c97a59b7cffcad22418ef2b96aa/lib/python3.11/concurrent/futures/thread.py\", line 58, in run\n    result = self.fn(*self.args, **self.kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/giuliano/miniconda3/envs/mulled-v1-dcee9f26cd5ca519fee179179957a800bc006c97a59b7cffcad22418ef2b96aa/lib/python3.11/site-packages/te_algorithms/gee/util.py\", line 529, in export\n    \"uris\": task.get_uris(),\n            ^^^^^^^^^^^^^^^\n  File \"/home/giuliano/miniconda3/envs/mulled-v1-dcee9f26cd5ca519fee179179957a800bc006c97a59b7cffcad22418ef2b96aa/lib/python3.11/site-packages/te_algorithms/gee/util.py\", line 195, in get_uris\n    raise GEETaskFailure(self.task)\nte_algorithms.gee.GEETaskFailure: Task AD4ISJNXKALSHVXMHTC4KIFG failed\n",
                    "stdout": "/media/agritech/tmp/tmpsmdvi0sb/files/0/2/3/dataset_023118e2-5846-4709-9677-964ef7b02dcf.dat\nGEOGCS[\"WGS 84\",DATUM[\"WGS_1984\",SPHEROID[\"WGS 84\",6378137,298.257223563,AUTHORITY[\"EPSG\",\"7030\"]],AUTHORITY[\"EPSG\",\"6326\"]],PRIMEM[\"Greenwich\",0,AUTHORITY[\"EPSG\",\"8901\"]],UNIT[\"degree\",0.0174532925199433,AUTHORITY[\"EPSG\",\"9122\"]],AUTHORITY[\"EPSG\",\"4326\"]]\nTrendsEarth-LPD-5\n",
                    "tool_id": "te_productivity",
                    "tool_stderr": "Loading parameters.\nExecution ID is None\nRunning productivity indicators.\nEntering productivity_trajectory function.\nEntering p_restrend function\nEntering ndvi_trend function.\nEntering linear_trend function\nEntering productivity_performance function.\nEntering productivity_state function.\nConverting output to TEImageV2 format\nExporting to cloud storage.\nStarting GEE task AD4ISJNXKALSHVXMHTC4KIFG.\nException in thread Thread-1:\nTraceback (most recent call last):\n  File \"/home/giuliano/miniconda3/envs/mulled-v1-dcee9f26cd5ca519fee179179957a800bc006c97a59b7cffcad22418ef2b96aa/lib/python3.11/threading.py\", line 1038, in _bootstrap_inner\n    self.run()\n  File \"/home/giuliano/miniconda3/envs/mulled-v1-dcee9f26cd5ca519fee179179957a800bc006c97a59b7cffcad22418ef2b96aa/lib/python3.11/site-packages/te_algorithms/gee/util.py\", line 115, in run\n    self.poll_for_completion()\n  File \"/home/giuliano/miniconda3/envs/mulled-v1-dcee9f26cd5ca519fee179179957a800bc006c97a59b7cffcad22418ef2b96aa/lib/python3.11/site-packages/te_algorithms/gee/util.py\", line 109, in poll_for_completion\n    return get_status(self)\n           ^^^^^^^^^^^^^^^^\n  File \"/home/giuliano/miniconda3/envs/mulled-v1-dcee9f26cd5ca519fee179179957a800bc006c97a59b7cffcad22418ef2b96aa/lib/python3.11/site-packages/backoff/_sync.py\", line 48, in retry\n    ret = target(*args, **kwargs)\n          ^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/giuliano/miniconda3/envs/mulled-v1-dcee9f26cd5ca519fee179179957a800bc006c97a59b7cffcad22418ef2b96aa/lib/python3.11/site-packages/te_algorithms/gee/util.py\", line 104, in get_status\n    self.logger.send_progress(self.task.status().get(\"progress\", 0.0))\n    ^^^^^^^^^^^^^^^^^^^^^^^^^\nAttributeError: 'Logger' object has no attribute 'send_progress'\nFailed to list uris for results from <Task AD4ISJNXKALSHVXMHTC4KIFG EXPORT_IMAGE: None_1_productivity_Int16_1 (UNSUBMITTED)>\nTraceback (most recent call last):\n  File \"/home/giuliano/Scaricati/trends_earth/galaxy_fix_tool/te_productivity.py\", line 51, in <module>\n    output_data = productivity.run(params=input_data, logger = logger)\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/giuliano/Scaricati/trends_earth/galaxy_fix_tool/productivity.py\", line 148, in run\n    final_output = schema.load(res[0].result())\n                               ^^^^^^^^^^^^^^^\n  File \"/home/giuliano/miniconda3/envs/mulled-v1-dcee9f26cd5ca519fee179179957a800bc006c97a59b7cffcad22418ef2b96aa/lib/python3.11/concurrent/futures/_base.py\", line 449, in result\n    return self.__get_result()\n           ^^^^^^^^^^^^^^^^^^^\n  File \"/home/giuliano/miniconda3/envs/mulled-v1-dcee9f26cd5ca519fee179179957a800bc006c97a59b7cffcad22418ef2b96aa/lib/python3.11/concurrent/futures/_base.py\", line 401, in __get_result\n    raise self._exception\n  File \"/home/giuliano/miniconda3/envs/mulled-v1-dcee9f26cd5ca519fee179179957a800bc006c97a59b7cffcad22418ef2b96aa/lib/python3.11/concurrent/futures/thread.py\", line 58, in run\n    result = self.fn(*self.args, **self.kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/giuliano/miniconda3/envs/mulled-v1-dcee9f26cd5ca519fee179179957a800bc006c97a59b7cffcad22418ef2b96aa/lib/python3.11/site-packages/te_algorithms/gee/util.py\", line 529, in export\n    \"uris\": task.get_uris(),\n            ^^^^^^^^^^^^^^^\n  File \"/home/giuliano/miniconda3/envs/mulled-v1-dcee9f26cd5ca519fee179179957a800bc006c97a59b7cffcad22418ef2b96aa/lib/python3.11/site-packages/te_algorithms/gee/util.py\", line 195, in get_uris\n    raise GEETaskFailure(self.task)\nte_algorithms.gee.GEETaskFailure: Task AD4ISJNXKALSHVXMHTC4KIFG failed\n",
                    "tool_stdout": "/media/agritech/tmp/tmpsmdvi0sb/files/0/2/3/dataset_023118e2-5846-4709-9677-964ef7b02dcf.dat\nGEOGCS[\"WGS 84\",DATUM[\"WGS_1984\",SPHEROID[\"WGS 84\",6378137,298.257223563,AUTHORITY[\"EPSG\",\"7030\"]],AUTHORITY[\"EPSG\",\"6326\"]],PRIMEM[\"Greenwich\",0,AUTHORITY[\"EPSG\",\"8901\"]],UNIT[\"degree\",0.0174532925199433,AUTHORITY[\"EPSG\",\"9122\"]],AUTHORITY[\"EPSG\",\"4326\"]]\nTrendsEarth-LPD-5\n",
                    "traceback": null,
                    "update_time": "2023-05-17T17:34:24.135578",
                    "user_email": "planemo@galaxyproject.org"
                },
                "output_problems": [
                    "Job in error state.. tool_id: te_productivity, exit_code: 1, stderr: Loading parameters.\nExecution ID is None\nRunning productivity indicators.\nEntering productivity_trajectory function.\nEntering p_restrend function\nEntering ndvi_trend function.\nEntering linear_trend function\nEntering productivity_performance function.\nEntering productivity_state function.\nConverting output to TEImageV2 format\nExporting to cloud storage.\nStarting GEE task AD4ISJNXKALSHVXMHTC4KIFG.\nException in thread Thread-1:\nTraceback (most recent call last):\n  File \"/home/giuliano/miniconda3/envs/mulled-v1-dcee9f26cd5ca519fee179179957a800bc006c97a59b7cffcad22418ef2b96aa/lib/python3.11/threading.py\", line 1038, in _bootstrap_inner\n    self.run()\n  File \"/home/giuliano/miniconda3/envs/mulled-v1-dcee9f26cd5ca519fee179179957a800bc006c97a59b7cffcad22418ef2b96aa/lib/python3.11/site-packages/te_algorithms/gee/util.py\", line 115, in run\n    self.poll_for_completion()\n  File \"/home/giuliano/miniconda3/envs/mulled-v1-dcee9f26cd5ca519fee179179957a800bc006c97a59b7cffcad22418ef2b96aa/lib/python3.11/site-packages/te_algorithms/gee/util.py\", line 109, in poll_for_completion\n    return get_status(self)\n           ^^^^^^^^^^^^^^^^\n  File \"/home/giuliano/miniconda3/envs/mulled-v1-dcee9f26cd5ca519fee179179957a800bc006c97a59b7cffcad22418ef2b96aa/lib/python3.11/site-packages/backoff/_sync.py\", line 48, in retry\n    ret = target(*args, **kwargs)\n          ^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/giuliano/miniconda3/envs/mulled-v1-dcee9f26cd5ca519fee179179957a800bc006c97a59b7cffcad22418ef2b96aa/lib/python3.11/site-packages/te_algorithms/gee/util.py\", line 104, in get_status\n    self.logger.send_progress(self.task.status().get(\"progress\", 0.0))\n    ^^^^^^^^^^^^^^^^^^^^^^^^^\nAttributeError: 'Logger' object has no attribute 'send_progress'\nFailed to list uris for results from <Task AD4ISJNXKALSHVXMHTC4KIFG EXPORT_IMAGE: None_1_productivity_Int16_1 (UNSUBMITTED)>\nTraceback (most recent call last):\n  File \"/home/giuliano/Scaricati/trends_earth/galaxy_fix_tool/te_productivity.py\", line 51, in <module>\n    output_data = productivity.run(params=input_data, logger = logger)\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/giuliano/Scaricati/trends_earth/galaxy_fix_tool/productivity.py\", line 148, in run\n    final_output = schema.load(res[0].result())\n                               ^^^^^^^^^^^^^^^\n  File \"/home/giuliano/miniconda3/envs/mulled-v1-dcee9f26cd5ca519fee179179957a800bc006c97a59b7cffcad22418ef2b96aa/lib/python3.11/concurrent/futures/_base.py\", line 449, in result\n    return self.__get_result()\n           ^^^^^^^^^^^^^^^^^^^\n  File \"/home/giuliano/miniconda3/envs/mulled-v1-dcee9f26cd5ca519fee179179957a800bc006c97a59b7cffcad22418ef2b96aa/lib/python3.11/concurrent/futures/_base.py\", line 401, in __get_result\n    raise self._exception\n  File \"/home/giuliano/miniconda3/envs/mulled-v1-dcee9f26cd5ca519fee179179957a800bc006c97a59b7cffcad22418ef2b96aa/lib/python3.11/concurrent/futures/thread.py\", line 58, in run\n    result = self.fn(*self.args, **self.kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/giuliano/miniconda3/envs/mulled-v1-dcee9f26cd5ca519fee179179957a800bc006c97a59b7cffcad22418ef2b96aa/lib/python3.11/site-packages/te_algorithms/gee/util.py\", line 529, in export\n    \"uris\": task.get_uris(),\n            ^^^^^^^^^^^^^^^\n  File \"/home/giuliano/miniconda3/envs/mulled-v1-dcee9f26cd5ca519fee179179957a800bc006c97a59b7cffcad22418ef2b96aa/lib/python3.11/site-packages/te_algorithms/gee/util.py\", line 195, in get_uris\n    raise GEETaskFailure(self.task)\nte_algorithms.gee.GEETaskFailure: Task AD4ISJNXKALSHVXMHTC4KIFG failed\n.",
                    "Job in error state.. tool_id: te_productivity, exit_code: 1, stderr: Loading parameters.\nExecution ID is None\nRunning productivity indicators.\nEntering productivity_trajectory function.\nEntering p_restrend function\nEntering ndvi_trend function.\nEntering linear_trend function\nEntering productivity_performance function.\nEntering productivity_state function.\nConverting output to TEImageV2 format\nExporting to cloud storage.\nStarting GEE task AD4ISJNXKALSHVXMHTC4KIFG.\nException in thread Thread-1:\nTraceback (most recent call last):\n  File \"/home/giuliano/miniconda3/envs/mulled-v1-dcee9f26cd5ca519fee179179957a800bc006c97a59b7cffcad22418ef2b96aa/lib/python3.11/threading.py\", line 1038, in _bootstrap_inner\n    self.run()\n  File \"/home/giuliano/miniconda3/envs/mulled-v1-dcee9f26cd5ca519fee179179957a800bc006c97a59b7cffcad22418ef2b96aa/lib/python3.11/site-packages/te_algorithms/gee/util.py\", line 115, in run\n    self.poll_for_completion()\n  File \"/home/giuliano/miniconda3/envs/mulled-v1-dcee9f26cd5ca519fee179179957a800bc006c97a59b7cffcad22418ef2b96aa/lib/python3.11/site-packages/te_algorithms/gee/util.py\", line 109, in poll_for_completion\n    return get_status(self)\n           ^^^^^^^^^^^^^^^^\n  File \"/home/giuliano/miniconda3/envs/mulled-v1-dcee9f26cd5ca519fee179179957a800bc006c97a59b7cffcad22418ef2b96aa/lib/python3.11/site-packages/backoff/_sync.py\", line 48, in retry\n    ret = target(*args, **kwargs)\n          ^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/giuliano/miniconda3/envs/mulled-v1-dcee9f26cd5ca519fee179179957a800bc006c97a59b7cffcad22418ef2b96aa/lib/python3.11/site-packages/te_algorithms/gee/util.py\", line 104, in get_status\n    self.logger.send_progress(self.task.status().get(\"progress\", 0.0))\n    ^^^^^^^^^^^^^^^^^^^^^^^^^\nAttributeError: 'Logger' object has no attribute 'send_progress'\nFailed to list uris for results from <Task AD4ISJNXKALSHVXMHTC4KIFG EXPORT_IMAGE: None_1_productivity_Int16_1 (UNSUBMITTED)>\nTraceback (most recent call last):\n  File \"/home/giuliano/Scaricati/trends_earth/galaxy_fix_tool/te_productivity.py\", line 51, in <module>\n    output_data = productivity.run(params=input_data, logger = logger)\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/giuliano/Scaricati/trends_earth/galaxy_fix_tool/productivity.py\", line 148, in run\n    final_output = schema.load(res[0].result())\n                               ^^^^^^^^^^^^^^^\n  File \"/home/giuliano/miniconda3/envs/mulled-v1-dcee9f26cd5ca519fee179179957a800bc006c97a59b7cffcad22418ef2b96aa/lib/python3.11/concurrent/futures/_base.py\", line 449, in result\n    return self.__get_result()\n           ^^^^^^^^^^^^^^^^^^^\n  File \"/home/giuliano/miniconda3/envs/mulled-v1-dcee9f26cd5ca519fee179179957a800bc006c97a59b7cffcad22418ef2b96aa/lib/python3.11/concurrent/futures/_base.py\", line 401, in __get_result\n    raise self._exception\n  File \"/home/giuliano/miniconda3/envs/mulled-v1-dcee9f26cd5ca519fee179179957a800bc006c97a59b7cffcad22418ef2b96aa/lib/python3.11/concurrent/futures/thread.py\", line 58, in run\n    result = self.fn(*self.args, **self.kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/giuliano/miniconda3/envs/mulled-v1-dcee9f26cd5ca519fee179179957a800bc006c97a59b7cffcad22418ef2b96aa/lib/python3.11/site-packages/te_algorithms/gee/util.py\", line 529, in export\n    \"uris\": task.get_uris(),\n            ^^^^^^^^^^^^^^^\n  File \"/home/giuliano/miniconda3/envs/mulled-v1-dcee9f26cd5ca519fee179179957a800bc006c97a59b7cffcad22418ef2b96aa/lib/python3.11/site-packages/te_algorithms/gee/util.py\", line 195, in get_uris\n    raise GEETaskFailure(self.task)\nte_algorithms.gee.GEETaskFailure: Task AD4ISJNXKALSHVXMHTC4KIFG failed\n."
                ],
                "status": "failure",
                "test_index": 0,
                "time_seconds": 35.10209035873413,
                "tool_id": "te_productivity",
                "tool_version": "2.1.14"
            },
            "has_data": true,
            "id": "te_productivity-0"
        }
    ],
    "version": "0.1"
}